export const BASE_URL = 'http://localhost:8080'
export const PO_REGISTER = '/poRegister'
export const FIN_YEAR = '/finYear'
export const SUPPLIER = '/supplier'
export const PO_DATA = '/poData'
export const MIS_DASHBOARD = '/misDashboard'
